name: daily-build-ccda

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/daily-build-executor.yml
    secrets: inherit
    with:
      working_dir: .
